gg.jte.development-mode=true
spring.application.name=CodeExample

# Tell Hibernate to create tables if they don't exist
spring.jpa.hibernate.ddl-auto=create-only

# Also add this to see the SQL Hibernate generates ? very educational!
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.datasource.url=jdbc:mysql://localhost:3306/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# A long random secret ? used to sign and verify tokens
jwt.secret=3f8b2c1d9e4a7f6b0c5d2e8a1b4f7c9d3e6b0a2f5c8d1e4b7a0c3f6d9e2b5a8
jwt.expiration=86400000
# 86400000 ms = 24 hours


#admin.email=admin@filmstudio.com
#admin.password=ChangeMe123!