gg.jte.development-mode=true
spring.application.name=CodeExample

# SQL Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#DATABSE
spring.datasource.url=jdbc:mysql://localhost:3306/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# A long random secret ? used to sign and verify tokens
jwt.secret=3f8b2c1d9e4a7f6b0c5d2e8a1b4f7c9d3e6b0a2f5c8d1e4b7a0c3f6d9e2b5a8
jwt.expiration=86400000
# 86400000 ms = 24 hours

# Mailtrap: fake inbox for development
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=59b86f58a2a92b
spring.mail.password=169070b08e0546
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Google OAuth2 UPDATE WITH CORRECT PASSWORDS
spring.security.oauth2.client.registration.google.client-id=${YOUR_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${YOUR_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile


spring.config.import=file:./.env[.properties]

spring.docker.compose.lifecycle-management=start_only
spring.devtools.livereload.enabled=true
s3.endpoint=http://localhost:3900
s3.region=garage
s3.access-key=${S3_ACCESS_KEY}
s3.secret-key=${S3_SECRET_KEY}

# Set to false during development to skip authentication
# MUST be true before any demo or production deployment!
app.security.enabled=false

# Production default ? always secure
cookie.secure=true

# application-local.properties ? add these:
S3_ACCESS_KEY=dummy-key-for-local
S3_SECRET_KEY=dummy-secret-for-local
S3_BUCKET_NAME=dummy-bucket
S3_REGION=eu-north-1
S3_ENDPOINT=http://localhost:9000
