gg.jte.development-mode=true
spring.application.name=CodeExample

spring.datasource.url=jdbc:mysql://localhost:3306/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.docker.compose.lifecycle-management=start_only
spring.devtools.livereload.enabled=true
