CREATE TABLE IF NOT EXISTS EVENT_PUBLICATION (
                                                 ID               BINARY(16) NOT NULL,
    COMPLETION_DATE  DATETIME(6),
    EVENT_TYPE       VARCHAR(512) NOT NULL,
    LISTENER_ID      VARCHAR(512) NOT NULL,
    PUBLICATION_DATE DATETIME(6) NOT NULL,
    SERIALIZED_EVENT TEXT NOT NULL,
    PRIMARY KEY (ID)
    ) ENGINE=InnoDB;


CREATE INDEX event_publication_by_completion_date_idx
    ON EVENT_PUBLICATION (COMPLETION_DATE);